// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sharks.Checkpoint02.Persistencias;

namespace Sharks.Checkpoint02.Migrations
{
    [DbContext(typeof(SharksContext))]
    [Migration("20211031043809_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sharks.Checkpoint02.Models.Editora", b =>
                {
                    b.Property<int>("EditoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("Date")
                        .HasColumnName("Dt_Inicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EditoraId");

                    b.ToTable("Tbl_Editora");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EnderecoId");

                    b.ToTable("Tbl_Endereco");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.Escritor", b =>
                {
                    b.Property<int>("EscritorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("Date")
                        .HasColumnName("Dt_Nascimento");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("EscritorId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Tbl_Escritor");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.Livro", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Lancamento");

                    b.Property<int?>("EditoraId")
                        .HasColumnType("int");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<bool>("Infantil")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Paginas")
                        .HasColumnType("int");

                    b.HasKey("LivroId");

                    b.HasIndex("EditoraId");

                    b.ToTable("Tbl_Livro");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.LivroEscritor", b =>
                {
                    b.Property<int>("EscritorId")
                        .HasColumnType("int");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.HasKey("EscritorId", "LivroId");

                    b.HasIndex("LivroId");

                    b.ToTable("Tbl_Livro_Escritor");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.Escritor", b =>
                {
                    b.HasOne("Sharks.Checkpoint02.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.Livro", b =>
                {
                    b.HasOne("Sharks.Checkpoint02.Models.Editora", "Editora")
                        .WithMany("Livros")
                        .HasForeignKey("EditoraId");

                    b.Navigation("Editora");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.LivroEscritor", b =>
                {
                    b.HasOne("Sharks.Checkpoint02.Models.Escritor", "Escritor")
                        .WithMany("LivrosEscritores")
                        .HasForeignKey("EscritorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sharks.Checkpoint02.Models.Livro", "Livro")
                        .WithMany("LivrosEscritores")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escritor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.Editora", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.Escritor", b =>
                {
                    b.Navigation("LivrosEscritores");
                });

            modelBuilder.Entity("Sharks.Checkpoint02.Models.Livro", b =>
                {
                    b.Navigation("LivrosEscritores");
                });
#pragma warning restore 612, 618
        }
    }
}
